version: "3.9"
services:
  backend:
    build:
      context: ./server
    container_name: backend-container
    ports:
      - "9876:8080"
    environment:
      PORT: 8080
      NODE_ENV: "development"
      REDIS_SERVICE: "ON"
      REDIS_INDUSTRY_LIST: "ON"
      MONGO_URI: "mongodb://root:rootpassword@mongodb_server:27017/tms?authSource=admin"
      REDIS_URL: redis://redis-server:6379
    depends_on:
      - redis-server
      - mongodb_server
  frontend:
    build:
      context: ./client
    container_name: frontend-container
    ports:
      - "8000:8000"
    environment:
      VITE_SERVER_URL: "http://localhost:9876"
  redis-server:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: "redis-container"
  mongodb_server:
    image: mongo:jammy
    restart: always
    container_name: mongodb_server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - "mongodb_server:/data/db"
volumes:
  mongodb_server: {}
