version: "3.9"
services:
  backend:
    build:
      context: ./server
    container_name: backend-container
    ports:
      - "9876:8080"
    environment:
      PORT: 8080
      NODE_ENV: "development"
      REDIS_SERVICE: "ON"
      REDIS_INDUSTRY_LIST: "ON"
      MONGO_URI: "mongodb://gulshan:1alyxstar@localhost:27017/social?authSource=admin"
      REDIS_URL: redis://redis-server:6379
    depends_on:
      - redis-server
  frontend:
    build:
      context: ./client
    container_name: frontend-container
    ports:
      - "8000:8000"
    environment:
      VITE_SERVER_URL: "http://localhost:9876"
  redis-server:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: "redis-container"
